Repository developmentseed/stac-auth-proxy, pull requests merged in 2025-07, with the labels that each got.

#62 feat(config): add root path GET requests to default public endpoints
  src/stac_auth_proxy/config.py
Labels: feat

#66 refactor(cql2-middleware): breakup cql2 middleware
  src/stac_auth_proxy/app.py
  src/stac_auth_proxy/middleware/ApplyCql2FilterMiddleware.py
  src/stac_auth_proxy/middleware/Cql2ApplyFilterBodyMiddleware.py
  src/stac_auth_proxy/middleware/Cql2ApplyFilterQueryStringMiddleware.py
  src/stac_auth_proxy/middleware/Cql2BuildFilterMiddleware.py
  src/stac_auth_proxy/middleware/Cql2ValidateResponseBodyMiddleware.py
  src/stac_auth_proxy/middleware/__init__.py
Labels: refactor

#70 fix: process links w/o the prefix
  src/stac_auth_proxy/middleware/ProcessLinksMiddleware.py
  tests/test_process_links.py
Labels: fix

#76 fix: ensure OPTIONS requests are sent upstream without auth check
  src/stac_auth_proxy/app.py
  src/stac_auth_proxy/middleware/EnforceAuthMiddleware.py
  src/stac_auth_proxy/middleware/UpdateOpenApiMiddleware.py
  tests/conftest.py
  tests/test_authn.py
  tests/test_openapi.py
Labels: fix
